version: 2.1

.env_xdebug: &env_xdebug
  XDEBUG_MODE: 'coverage'

.env_composer: &env_composer
  COMPOSER_ALLOW_SUPERUSER: '1'
  COMPOSER_NO_INTERACTION: '1'
  COMPOSER_MEMORY_LIMIT: '-1'
  COMPOSER_DISABLE_XDEBUG_WARN: '1'
  COMPOSER_CACHE_DIR: '/root/.cache/composer'

.env_yarn: &env_yarn
  YARN_CACHE_FOLDER: '/root/.cache/yarn'

.env_test: &env_test
  SIMPLETEST_BASE_URL: 'http://localhost:8888'
  DTT_BASE_URL: 'http://localhost:8888'
  SIMPLETEST_DB: 'sqlite://sites/default/db.default.default.sqlite'
  UNISH_DB_URL: 'sqlite://sites/default/db.default.default.sqlite'
  UNISH_NO_TIMEOUTS: 'y'

orbs:
  codecov: 'codecov/codecov@1.1.2'

executors:
  php800:
    environment:
      <<: *env_xdebug
      <<: *env_composer
      <<: *env_yarn
      <<: *env_test

    docker:
      -
        name: 'main'
        image: 'misterio92/ci-php-node:5.0'

  php704:
    environment:
      <<: *env_xdebug
      <<: *env_composer
      <<: *env_yarn
      <<: *env_test

    docker:
      -
        name: 'main'
        image: 'misterio92/ci-php-node:4.0'

commands:
  install_yarn:
    description: 'Install "yarn" NPM package'
    steps:
      -
        run:
          name: 'Install Yarn'
          command: 'npm install -g yarn@1.22.10'
      -
        run:
          name: 'Yarn - Config set - cache-folder'
          command: 'yarn config set cache-folder "${YARN_CACHE_FOLDER}"'

  install_php_requirements:
    description: ''
    steps:
      -
        run:
          name: 'Install required PHP extensions'
          command: |
            apt-get update
            apt-get install -y \
              php-xdebug \
              "php$(php -r 'echo mb_substr(PHP_VERSION, 0, 3);')-phpdbg"

  composer_install:
    description: 'Install Composer dependencies with cache restore and save'
    steps:
      -
        restore_cache:
          name: 'Composer - cache restore'
          keys:
            - 'composer-{{ checksum "./composer.lock" }}-v1'
      -
        run:
          name: 'Composer - install'
          command: >
            composer install --no-progress
      -
        save_cache:
          name: 'Composer - cache save'
          key: 'composer-{{ checksum "./composer.lock" }}-v1'
          paths:
            - '/root/.cache/composer/'

  lint:
    description: 'Run linters'
    steps:
      -
        run:
          name: 'Run linters'
          command: 'bin/robo lint'

  test:
    description: 'Run tests'
    steps:
      -
        restore_cache:
          name: 'Yarn - cache restore'
          keys:
            - 'yarn-{{ checksum "./tests/fixtures/project_01/docroot/themes/custom/dummy_t1/package.json" }}-v1'
      -
        run:
          name: 'Run tests - Unit'
          command: 'bin/robo test:phpunit Unit'
      -
        codecov/upload:
          flags: 'unit'
          file: './reports/machine/coverage/coverage.unit.xml'
      -
        run:
          name: 'Run tests - Integration'
          command: |
            cd tests/fixtures/project_01/docroot
            php -S localhost:8888 .ht.router.php 1>/dev/null 2>/dev/null &
            cd ../../../..
            bin/robo test:phpunit Integration
      -
        codecov/upload:
          flags: 'integration'
          file: './reports/machine/coverage/coverage.integration.xml'
      -
        store_test_results:
          name: 'Store test results'
          path: './reports/machine/unit'
      -
        save_cache:
          name: 'Yarn - cache save'
          key: 'yarn-{{ checksum "./tests/fixtures/project_01/docroot/themes/custom/dummy_t1/package.json" }}-v1'
          paths:
            - '/root/.cache/yarn/'

jobs:
  build:
    executor: 'php704'
    working_directory: '~/repo'
    steps:
      - 'checkout'
      - 'composer_install'
  lint:
    executor: 'php704'
    working_directory: '~/repo'
    steps:
      - 'checkout'
      - 'composer_install'
      - 'lint'
  test_php800:
    executor: 'php800'
    working_directory: '~/repo'
    steps:
      - 'checkout'
      - 'install_yarn'
      - 'install_php_requirements'
      - 'composer_install'
      - 'test'
  test_php704:
    executor: 'php704'
    working_directory: '~/repo'
    steps:
      - 'checkout'
      - 'install_yarn'
      - 'install_php_requirements'
      - 'composer_install'
      - 'test'

workflows:
  lint_and_test:
    jobs:
      -
        build: {}
      -
        lint:
          requires:
            - build
      -
        test_php704:
          requires:
            - build
      -
        test_php800:
          requires:
            - build
