version: 2.1

.env_app: &env_app
  APP_COMPOSER_VERSION: '1.10.20'
  APP_COMPOSER_HASH: '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3'
  SHELL: '/bin/bash'

.env_composer: &env_composer
  COMPOSER_NO_INTERACTION: '1'
  COMPOSER_MEMORY_LIMIT: '-1'
  COMPOSER_DISABLE_XDEBUG_WARN: '1'
  COMPOSER_CACHE_DIR: '/home/circleci/.cache/composer'

.env_test: &env_test
  SIMPLETEST_BASE_URL: 'http://localhost:8888'
  DTT_BASE_URL: 'http://localhost:8888'
  SIMPLETEST_DB: 'sqlite://sites/default/db.default.default.sqlite'
  UNISH_DB_URL: 'sqlite://sites/default/db.default.default.sqlite'
  UNISH_NO_TIMEOUTS: 'y'

orbs:
  codecov: 'codecov/codecov@1.0.4'

executors:
  php704:
    environment:
      <<: *env_app
      <<: *env_composer
      <<: *env_test

    docker:
      -
        name: 'main'
        image: 'misterio92/ci-php-node:4.0'

  php703:
    environment:
      <<: *env_app
      <<: *env_composer
      <<: *env_test

    docker:
      -
        name: 'main'
        image: 'misterio92/ci-php-node:3.0'

commands:
  install_composer:
    description: 'Install Composer CLI tool'
    steps:
      -
        run:
          name: ''
          command: |2
            mkdir -p "${HOME}/.local/bin"
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('sha384', 'composer-setup.php') === getenv('APP_COMPOSER_HASH')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php \
                --filename    'composer' \
                --install-dir "${HOME}/.local/bin" \
                --version     "${APP_COMPOSER_VERSION}"
            php -r "unlink('composer-setup.php');"
            rm -rf '/usr/local/bin/composer'
            cp "${HOME}/.local/bin/composer" '/usr/local/bin/composer'
            whereis composer
            which composer
            type composer
            composer --version

  install_yarn:
    description: 'Install "yarn" NPM package'
    steps:
      -
        run:
          name: 'Install Yarn'
          command: 'npm install -g yarn@1.15.2'

  install_php_requirements:
    description: ''
    steps:
      -
        run:
          name: 'Install required PHP extensions'
          command: |
            apt-get update
            apt-get install -y \
              php-xdebug \
              "php$(php -r 'echo mb_substr(PHP_VERSION, 0, 3);')-phpdbg"

  composer_install:
    description: 'Install Composer dependencies with cache restore and save'
    steps:
      -
        restore_cache:
          name: 'Composer - cache restore'
          keys:
            - 'composer-{{ checksum "./composer.lock" }}-v1'
      -
        run:
          name: 'Composer - install'
          command: >
            composer install --no-progress
      -
        save_cache:
          name: 'Composer - cache save'
          key: 'composer-{{ checksum "./composer.lock" }}-v1'
          paths:
            - '~/.cache/composer'

  lint:
    description: 'Run linters'
    steps:
      -
        run:
          name: 'Run linters'
          command: 'bin/robo lint'

  test:
    description: 'Run tests'
    steps:
      -
        run:
          name: 'Run tests - Unit'
          command: 'bin/robo test:phpunit Unit'
      -
        codecov/upload:
          flags: 'unit'
          file: './reports/machine/coverage/coverage.unit.xml'
      -
        run:
          name: 'Run tests - Integration'
          command: |
            cd tests/fixtures/project_01/docroot
            php -S localhost:8888 .ht.router.php 1>/dev/null 2>/dev/null &
            cd ../../../..
            bin/robo test:phpunit Integration
      -
        codecov/upload:
          flags: 'integration'
          file: './reports/machine/coverage/coverage.integration.xml'
      -
        store_test_results:
          name: 'Store unit test results'
          path: './reports/machine/unit'

jobs:
  build:
    executor: 'php703'
    working_directory: '~/repo'
    steps:
      - 'checkout'
      - 'install_composer'
      - 'composer_install'
  lint:
    executor: 'php703'
    working_directory: '~/repo'
    steps:
      - 'checkout'
      - 'install_composer'
      - 'composer_install'
      - 'lint'
  test_php704:
    executor: 'php704'
    working_directory: '~/repo'
    steps:
      - 'checkout'
      - 'install_composer'
      - 'install_yarn'
      - 'install_php_requirements'
      - 'composer_install'
      - 'test'
  test_php703:
    executor: 'php703'
    working_directory: '~/repo'
    steps:
      - 'checkout'
      - 'install_composer'
      - 'install_yarn'
      - 'install_php_requirements'
      - 'composer_install'
      - 'test'

workflows:
  lint_and_test:
    jobs:
      -
        build: {}
      -
        lint:
          requires:
            - build
      -
        test_php704:
          requires:
            - build
      -
        test_php703:
          requires:
            - build
