
version: 2

_custom:
    step__run__install_php_extensions: &step__run__install_php_extensions
        name: 'Install PHP extensions'
        command: |
            sudo apt-get -y install \
                libpng-dev \
                zlib1g-dev

            sudo docker-php-ext-install \
                gd \
                zip
    step__run__install_composer: &step__run__install_composer
        name: 'Install composer'
        command: |
            cd /tmp
            EXPECTED_SIGNATURE=$(curl -q https://composer.github.io/installer.sig)
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")

            if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
            then
                >&2 echo 'ERROR: Invalid installer signature'
                rm composer-setup.php

                exit 1
            fi

            sudo php composer-setup.php --quiet --install-dir /usr/local/bin --filename composer
            RESULT=$?
            rm composer-setup.php

            exit $RESULT
    step__restore_cache: &step__restore_cache
        name: 'Cache restore - "./vendor"'
        keys:
            - 'v1-dependencies-{{ checksum "composer.lock" }}'
            - 'v1-dependencies-'
    step__run__composer_install: &step__run__composer_install
        name: 'Build'
        command: 'composer install --no-interaction'
    step__run__composer_validate: &step__run__composer_validate
        name: 'Composer validate'
        command: 'composer validate'
    step__save_cache: &step__save_cache
        name: 'Cache save - "./vendor"'
        paths:
            - './vendor'
        key: 'v1-dependencies-{{ checksum "composer.lock" }}'
    step__run__phpcs: &step__run__phpcs
        name: 'Run linters'
        command: 'bin/phpcs'
    step__run__phpunit: &step__run__phpunit
        name: 'PHPUnit'
        command: |
            cd tests/fixtures/project_01/docroot
            php -S localhost:8888 .ht.router.php 1>/dev/null 2>/dev/null &
            cd ../../../..
            bin/phpunit
    step__store_test_results: &step__store_test_results
        path: 'reports/machine/unit/junit.xml'
    step__run__codecov: &step__run__codecov
        name: 'Publish the code coverage report on Codecov.io'
        when: 'always'
        command: >
            [ ! -s tests/_output/machine/coverage/*/coverage.xml ]
            || bash <(curl -s https://codecov.io/bash)
            || true

    job__lint_and_test: &job__lint_and_test
        working_directory: '~/repo'
        steps:
            - 'checkout'
            -
                run:
                    <<: *step__run__install_php_extensions
            -
                run:
                    <<: *step__run__install_composer
            -
                restore_cache:
                    <<: *step__restore_cache
            -
                run:
                    <<: *step__run__composer_validate
            -
                run:
                    <<: *step__run__composer_install
            -
                save_cache:
                    <<: *step__save_cache
            -
                run:
                    <<: *step__run__phpcs
            -
                run:
                    <<: *step__run__phpunit
            -
                store_test_results:
                    <<: *step__store_test_results
            -
                run:
                    <<: *step__run__codecov

jobs:
    php701__lint_and_test:
        <<: *job__lint_and_test
        docker:
            -
                image: 'circleci/php:7.1'
    php702__lint_and_test:
        <<: *job__lint_and_test
        docker:
            -
                image: 'circleci/php:7.2'
    php703__lint_and_test:
        <<: *job__lint_and_test
        docker:
            -
                image: 'circleci/php:7.3'

workflows:
    version: 2
    php701__lint_and_test:
        jobs:
            - 'php701__lint_and_test'
    php702__lint_and_test:
        jobs:
            - 'php702__lint_and_test'
    php703__lint_and_test:
        jobs:
            - 'php703__lint_and_test'
